---
title: "Making dotplots for EPEC"
output: 
  html_notebook:
    fig_width: 6
    fig_height: 5
editor_options: 
  chunk_output_type: inline
---


```{r lib-setup, results='hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(fig.width = 6)
knitr::opts_chunk$set(fig.height = 5)
library(tidyverse)
library(ggprism)
library(rcartocolor)
library(patchwork)
```

Define all helper functions and color choices
```{r helper, include=TRUE}
theme_set(theme_bw(base_size = 17) + theme(legend.title = element_text()))
#Set color choices from CARTOcolors
discrete_pal_choice <- "Bold"
cont_pal_choice <- "BluYl"
diverg_pal_choice <- "Geyser"
#Set color vectors
cont_colors <- carto_pal(name = cont_pal_choice)
chosen_cont_colors <- cont_colors [c(2,4,6,7)]
#Helper functions
calc_relative <- function(x) x/sum(x) * 100
#Set up paths for data, and results
data_path <- "short_infection_EPEC_reads/data/"
res_path <- "short_infection_EPEC_reads/results/"
```
Read in results
```{r import, fig.width=7, fig.height=5}
gse_dfs_names <- list.files(path = here::here(str_c(res_path,"tables/")), pattern = "GSEA")
#Read in the dfs
gse_dfs <- gse_dfs_names %>% 
  set_names(.,nm = .) %>% 
  map(~read_csv(file = here::here(str_c(res_path, "tables/",.x)))) 
#Get gene counts
gse_counts <- gse_dfs %>% 
  map(separate_rows,core_enrichment, sep = "/") %>% 
  map(summarise, Count = n(), .by = c("NES","Description","p.adjust")) %>% 
  map(mutate, Description = str_wrap(Description, width = 25))

#Plot the results
#pdf(here::here(str_c(res_path,"Functional profiling dotplots better colors.pdf")), width = 7, height = 5)
gse_counts %>% 
  iwalk(~print(ggplot(.x, aes(x = NES, y = fct_reorder(Description,NES), 
                              color = p.adjust, size = Count)) +
                 geom_point() + 
                 scale_color_gradient(low  = chosen_cont_colors [4], high = chosen_cont_colors [1]) +
                 scale_size(range = c(5,10)) +
                 labs(y = element_blank(), caption = .y) +
                 coord_cartesian(clip = "off", xlim = c(min(.x$NES)-0.2, max(.x$NES)+0.1)) + 
                 theme(axis.text.x = element_text(color = "black"),
                       axis.text.y = element_text(color = "black")) 
  ))
#dev.off()
```
```{r combine_time_gsea_plots, fig.width=9, fig.height=5}
gse_df <- gse_counts %>% 
  keep(str_detect(names(.), "Time")) %>% 
  imap(~mutate(.x, Time = .y)) %>% 
  reduce(bind_rows) %>% 
  mutate(Time = str_extract(Time, "[:digit:]+"),
         Time = fct_relevel(Time, "45","90"))
gsea_plot <- ggplot(gse_df, aes(x = NES, y = fct_reorder(Description,NES), 
                                color = p.adjust)) +
  geom_point(aes(size = Count)) + 
  scale_color_gradient(low  = chosen_cont_colors [4], high = chosen_cont_colors [1], name = "Adjusted p-value",
                       limits = c(0,0.035), breaks = c(0.01, 0.02, 0.03)) +
  scale_size(range = c(5,10)) +
  labs(y = element_blank()) +
  #geom_vline(xintercept = 0, linewidth = 1.2, linetype = "longdash", color = "grey50") +
  #geom_segment(aes(x = 0, xend = NES, yend = fct_reorder(Description,NES)), linewidth = 1.8) +
  coord_cartesian(clip = "off", xlim = c(min(gse_df$NES)-0.4, max(gse_df$NES)+0.3)) + 
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black")) +
  facet_wrap(~Time, nrow = 1) + 
  theme(axis.text.x = element_text(size = 15))
gsea_plot
#ggsave(here::here(str_c(res_path,"Functional profiling dotplots better colors.png")), gsea_plot, width = 9, height = 5, dpi = 1080)
#ggsave(here::here(str_c(res_path,"Functional profiling dotplots better colors.svg")), gsea_plot, width = 9, height = 5)
```


