---
title: "Correlation of EPEC and human reads in short infection"
output: 
  html_notebook: 
    fig_width: 6
    fig_height: 5
editor_options: 
  chunk_output_type: inline
---

```{r lib, results='hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(fig.width = 6)
knitr::opts_chunk$set(fig.height = 5)
library(greekLetters)
library(PCAtools)
library(pheatmap)
library(eulerr)
library(clusterProfiler)
library(psych)
library(tidyverse)
library(ggprism)
library(rcartocolor)
```

Define all helper functions and color choices
```{r helper, include=TRUE}
theme_set(theme_prism(base_size = 14) + theme(legend.title = element_text()))
#Set color choices from CARTOcolors
discrete_pal_choice <- "Bold"
cont_pal_choice <- "BluYl"
diverg_pal_choice <- "Geyser"
#Helper functions
calc_relative <- function(x) x/sum(x) * 100
#Set up paths for data, and results
data_path <- "short_infection_human_reads/data/"
res_path <- "short_infection_human_reads/results/final clean figures/"
```

Read in normalized counts and results

```{r import}
human_cnts <- read_csv(here::here(str_c(res_path,"tables/normalized counts.csv")))
human_res <- read_csv(here::here(str_c(res_path,"tables/EDAseq_normalized results comparing by time WT infection.csv")))
human_res_de <- human_res %>% 
  filter(if_any(.cols = contains("padj"), .fns = ~.x < 0.05)) %>% 
  filter(if_any(.cols = contains("log2"), .fns = ~abs(.x) > 1))
e_cnts <- read_csv(here::here(str_c("short_infection_EPEC_reads/results/tables/normalized_counts.csv")))
e_res <- read_csv(here::here(str_c("short_infection_EPEC_reads/results/tables/EDAseq_normalized results comparing by time WT infection.csv")))
e_res_vs_n <- read_csv(here::here(str_c("short_infection_EPEC_reads/results/tables/EDAseq_normalized results comparing  WT and EscN infection.csv")))
e_res_de <- e_res %>% 
  left_join(e_res_vs_n, by = c("geneid","true_name","true_biotype")) %>% 
  filter(if_any(.cols = contains("padj"), .fns = ~.x < 0.05)) %>% 
  filter(if_any(.cols = contains("log2"), .fns = ~abs(.x) > 1))
```
Get matrices
```{r mat-prep}
e_mat <- e_cnts %>% 
  filter(geneid %in% e_res_de$geneid) %>% 
  left_join(select(e_res_de, geneid, true_name), by = "geneid") %>% 
  column_to_rownames(var = "true_name") %>% 
  select(-geneid) %>% 
  as.matrix
e_mat_wt <- e_mat [,str_detect(colnames(e_mat), "WT")]
human_mat <- human_cnts %>% 
  filter(geneid %in% human_res_de$geneid) %>% 
  column_to_rownames(var = "true_name") %>% 
  select(where(is.numeric)) %>% 
  as.matrix()
human_mat_wt <- human_mat [,colnames(e_mat_wt)]
```

Run the Pearson correlations
```{r spear, fig.width=8, fig.height=6}
pear_wt <- WGCNA::corAndPvalue(x = t(e_mat_wt), y = t(human_mat_wt), method = "pearson", quick = 0.5)
cor_df <- reshape2::melt(pear_wt [["cor"]]) %>% 
  rename(cor = value) %>% 
  left_join(reshape2::melt(pear_wt [["p"]]), by = c("Var1","Var2")) %>% 
  rename(p = value) %>% 
  mutate(padj = p.adjust(p, method = "BH"))
#write_csv(cor_df,here::here(str_c(res_path,"tables/human-epec-pearson.csv")))
cor_df_select <- cor_df %>% 
  filter(padj < 0.05, abs(cor) > 0.75)
#write_tsv(cor_df_select, here::here(str_c(res_path,"tables/human_epec_pearson_select.tsv")))
```



